# Site
name: "The Blaze Times"
title: "The Blaze Times"
description: "Get the latest breaking news and insightful analysis with The Blaze Times. Stay updated on politics, culture, and more."
keywords: "latest news updates, political news, technology news, current affairs, India news"
logo: 'https://www.theblazetimes.in/logo.png'
image: "https://www.theblazetimes.in/the-blaze-times.jpeg"
favicon: 'favicon.ico'
disqus: 'the-blaze-times'
mailchimp-list: 'https://theblazetimes.us9.list-manage.com/subscribe/post?u=93fe5eb8eeceed33701ba0e8f&amp;id=ae9e5d4588&amp;f_id=00c6c2e1f0'
include: ["_pages"]
permalink: /:title/
timezone: "Asia/Kolkata"
x: "@theblazetimes_x"
author: "The Blaze Times"
facebook: "theblazetimes"
author_url: "https://gravatar.com/theblazetimes"
author_image: "https://www.gravatar.com/avatar/67accb20e06a4954e37ee7c6ea8790e0?s=250&d=mm&r=x"

# Authors
authors:
  The Blaze Times:
    name: The Blaze Times
    display_name: The Blaze Times
    gravatar: 67accb20e06a4954e37ee7c6ea8790e0
    email: theblazetimes@gmail.com
    web: https://www.theblazetimes.in
    twitter: https://twitter.com/theblazetimes_x
    description: "The Blaze Times delivers breaking news and analysis on politics, culture, and more. Stay informed with our expert commentary and timely updates."
  It Is Unique Official:
    name: It Is Unique Official
    display_name: It Is Unique Official
    gravatar: beb6bb7addac22582e879ea50bbacfa2
    email: itisuniqueofficial@gmail.com
    web: https://t.me/itisuniqueofficial
    twitter: https://twitter.com/itisuniquex
    description: "It Is Unique Official is a tech-focused brand by Jaydatt Khodave, offering programming tools, tutorials, and resources for developers."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-git-last-modified
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-4994341766136391"
adsense-data-ad-slot: "3578670127"

# Analytics (change to "enabled" to activate, enter your GA ID.)
analytics: "enabled"
google_analytics: "G-J47BDWDNY1"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
